# Generated by Django 5.0.6 on 2024-06-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0005_pelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.TimeField(null=True),
        ),
    ]
