# Generated by Django 5.0.6 on 2024-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0007_alter_pelicula_director_alter_pelicula_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='generos'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.FileField(blank=True, null=True, upload_to='portadas'),
        ),
    ]
